package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"testing"
)

// determinismTemplates is the canonical set of bundled templates that the
// engine guarantees byte-stable output for. Designer templates (abstract,
// blue-corporate, business-template, modern, modern-yellow) are intentionally
// excluded until go-slide-creator-vqad lands.
var determinismTemplates = []string{
	"forest-green",
	"midnight-blue",
	"modern-template",
	"warm-coral",
}

// goldenHashesPath holds the checked-in expected sha256 of basic-deck.json
// rendered against each template. The file is regenerated by
// scripts/rebaseline_golden_hashes.sh.
const goldenHashesPath = "testdata/golden_hashes.json"

// TestDeterministicCorpus asserts that rendering examples/basic-deck.json
// against every bundled template is:
//
//  1. byte-stable across two consecutive runs in the same process (no
//     timestamps, no nondeterministic IDs, no zip ordering jitter), and
//  2. byte-equal to the checked-in golden hash so unintentional drift is
//     caught loudly.
//
// SOURCE_DATE_EPOCH is pinned to a fixed value to satisfy the reproducible
// builds convention even though the engine does not currently embed
// timestamps — future regressions that start using time.Now() will be
// neutralised by the pinned epoch instead of breaking the test.
//
// Cross-platform: text-fit calculations route through internal/textcapacity
// which uses embedded Liberation Sans metrics, so the byte-identical
// guarantee holds on every platform the project supports. The golden-hash
// comparison is strict on linux (the CI canonical platform) and logs a
// notice on other platforms so developer machines do not fail spuriously
// when font shaping differences leak in via future code paths.
//
// Acceptance: go-slide-creator-l50r.
func TestDeterministicCorpus(t *testing.T) {
	projectRoot, err := filepath.Abs(filepath.Join("..", ".."))
	if err != nil {
		t.Fatalf("resolve project root: %v", err)
	}
	templatesDir := filepath.Join(projectRoot, "templates")
	examplePath := filepath.Join(projectRoot, "examples", "basic-deck.json")
	if _, err := os.Stat(examplePath); err != nil {
		t.Fatalf("missing fixture %s: %v", examplePath, err)
	}

	// Pin SOURCE_DATE_EPOCH for the lifetime of this test so any future
	// timestamp-using code paths produce stable bytes. t.Setenv restores
	// the original value automatically on test exit.
	t.Setenv("SOURCE_DATE_EPOCH", "1700000000")
	// Force a stable timezone so any future RFC3339-rendered metadata
	// does not shift bytes between developer machines.
	t.Setenv("TZ", "UTC")

	goldens := loadGoldenHashes(t, projectRoot)

	for _, tmpl := range determinismTemplates {
		tmpl := tmpl
		t.Run(tmpl, func(t *testing.T) {
			a := renderForDeterminism(t, templatesDir, examplePath, tmpl, "a")
			b := renderForDeterminism(t, templatesDir, examplePath, tmpl, "b")

			hashA := sha256Hex(t, a)
			hashB := sha256Hex(t, b)

			if hashA != hashB {
				t.Errorf("non-deterministic output for template %s:\n  run A: %s (%s)\n  run B: %s (%s)\n"+
					"diff hint: ./pptx2jpg <a> <b> to inspect the rendered slides",
					tmpl, hashA, a, hashB, b)
				return
			}

			expected, ok := goldens[tmpl]
			switch {
			case !ok:
				t.Logf("no golden hash recorded for %s — current: %s. Run scripts/rebaseline_golden_hashes.sh to seed.", tmpl, hashA)
			case expected != hashA:
				msg := fmt.Sprintf("golden hash drift for template %s:\n  expected: %s\n  actual:   %s\n"+
					"diff hint: ./pptx2jpg <golden.pptx> %s to inspect; rerun scripts/rebaseline_golden_hashes.sh after confirming the change is intentional",
					tmpl, expected, hashA, a)
				if runtime.GOOS == "linux" {
					t.Error(msg)
				} else {
					t.Logf("%s\n(non-linux platform: logged as info — CI on linux is the source of truth)", msg)
				}
			}
		})
	}
}

// renderForDeterminism converts examples/basic-deck.json against tmpl into a
// fresh tempdir-rooted PPTX path. The caller distinguishes parallel runs via
// the tag argument so the two outputs end up at different paths and can be
// compared by hash.
func renderForDeterminism(t *testing.T, templatesDir, examplePath, tmpl, tag string) string {
	t.Helper()

	caseDir := t.TempDir()

	// Patch the JSON in-flight so the output filename is stable across runs
	// without mutating the source fixture on disk.
	data, err := os.ReadFile(examplePath)
	if err != nil {
		t.Fatalf("read example: %v", err)
	}
	var input map[string]any
	if err := json.Unmarshal(data, &input); err != nil {
		t.Fatalf("parse example: %v", err)
	}
	input["template"] = tmpl
	outputFilename := "basic-deck_" + tmpl + ".pptx"
	input["output_filename"] = outputFilename

	patched, err := json.Marshal(input)
	if err != nil {
		t.Fatalf("marshal patched example: %v", err)
	}
	patchedJSON := filepath.Join(caseDir, "input_"+tag+".json")
	if err := os.WriteFile(patchedJSON, patched, 0o644); err != nil {
		t.Fatalf("write patched example: %v", err)
	}

	resultJSON := filepath.Join(caseDir, "result_"+tag+".json")
	// design_mode=free matches corpus_headless_test.go — the determinism
	// guarantee is orthogonal to the constrained-mode validator.
	if err := runJSONMode(patchedJSON, resultJSON, templatesDir, caseDir, "", false, false, tmpl, "off", false, "off", "free", false); err != nil {
		t.Fatalf("runJSONMode (%s, %s) failed: %v", tmpl, tag, err)
	}

	generated := filepath.Join(caseDir, outputFilename)
	if _, err := os.Stat(generated); err != nil {
		t.Fatalf("generated PPTX missing at %s: %v", generated, err)
	}
	return generated
}

func sha256Hex(t *testing.T, path string) string {
	t.Helper()
	contents, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	sum := sha256.Sum256(contents)
	return hex.EncodeToString(sum[:])
}

func loadGoldenHashes(t *testing.T, projectRoot string) map[string]string {
	t.Helper()
	path := filepath.Join(projectRoot, "cmd", "json2pptx", goldenHashesPath)
	raw, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return map[string]string{}
		}
		t.Fatalf("read %s: %v", path, err)
	}
	var goldens map[string]string
	if err := json.Unmarshal(raw, &goldens); err != nil {
		t.Fatalf("parse %s: %v", path, err)
	}
	// Surface unknown templates so a rebaseline drift doesn't quietly orphan entries.
	known := map[string]struct{}{}
	for _, tmpl := range determinismTemplates {
		known[tmpl] = struct{}{}
	}
	var orphans []string
	for tmpl := range goldens {
		if _, ok := known[tmpl]; !ok {
			orphans = append(orphans, tmpl)
		}
	}
	if len(orphans) > 0 {
		sort.Strings(orphans)
		t.Logf("golden_hashes.json contains entries for unknown templates: %v — remove or add to determinismTemplates", orphans)
	}
	return goldens
}
