package api

import (
	"net/http"
	"os"
	"path/filepath"
	"regexp"

	apierrors "github.com/sebahrens/json2pptx/internal/api/errors"
)

// validDownloadFilename matches only hex-encoded filenames with .pptx extension
// generated by generateUniqueFilename (32 hex chars + ".pptx").
var validDownloadFilename = regexp.MustCompile(`^[0-9a-f]{32}\.pptx$`)

// DownloadHandler returns an http.HandlerFunc for GET /api/v1/download/{filename}.
// It serves generated PPTX files from the output directory with path traversal protection.
func (cs *ConvertService) DownloadHandler() http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		filename := r.PathValue("filename")

		// Validate filename format to prevent path traversal
		if !validDownloadFilename.MatchString(filename) {
			writeError(w, http.StatusBadRequest, apierrors.CodeInvalidRequest,
				"Invalid filename", nil)
			return
		}

		filePath := filepath.Join(cs.outputDir, filename)

		// Check file exists
		info, err := os.Stat(filePath)
		if err != nil || info.IsDir() {
			writeError(w, http.StatusNotFound, apierrors.CodeFileNotFound,
				"File not found", nil)
			return
		}

		// Serve the file with appropriate headers
		w.Header().Set("Content-Type", "application/vnd.openxmlformats-officedocument.presentationml.presentation")
		w.Header().Set("Content-Disposition", "attachment; filename=\"presentation.pptx\"")
		http.ServeFile(w, r, filePath)
	}
}
