#!/usr/bin/env bash
# Writes the durations table scripts/ci_test_cmd_shards.sh balances shards by:
# "seconds TestName" for every top-level cmd/json2pptx test that added at least
# MIN_SECONDS (default 1) to its shard's wall time in a sharded run, slowest
# first.
#
# Input is the output of scripts/ci_test_cmd_shards.sh — a CI job log or a
# local run — on stdin or as file arguments. Only what the script printed
# between its "shard N" group markers is read, so a whole job log (with the
# other packages' tests in it) is fine, in any of the forms GitHub gives it:
#
#   gh run view <run-id> --log --job <job-id> | scripts/ci_test_durations.sh >scripts/ci_test_durations.txt
#   scripts/ci_test_durations.sh job-log.txt >scripts/ci_test_durations.txt
#
# Take the durations from CI, not from a laptop: the shards are balanced for
# the runner's four cores under -race.
set -euo pipefail
export LC_ALL=C

MIN="${MIN_SECONDS:-1}"
PARALLEL="${PARALLEL:-4}"
SOURCE="${DURATIONS_SOURCE:-}"

echo "# seconds TestName: top-level cmd/json2pptx tests that take ${MIN}s or more in"
echo "# CI's sharded -short -race run, slowest first. scripts/ci_test_cmd_shards.sh"
echo "# balances its shards by this table; a test not listed weighs"
echo "# CI_TEST_DEFAULT_WEIGHT there. Generated by scripts/ci_test_durations.sh from"
echo "# a job log; regenerate rather than edit."
if [ -n "$SOURCE" ]; then
  echo "# Source: $SOURCE"
fi

# A test or subtest that calls t.Parallel shares the binary's GOMAXPROCS slots
# with the others, so it adds about its reported seconds divided by PARALLEL
# (default 4, the runner's cores) to the shard's wall time. A parent reports
# only its own body: its parallel first-level subtests are added to it.
cat "$@" | awk -v min="$MIN" -v par="$PARALLEL" '
  {
    line = $0
    sub(/\r$/, "", line)
    # A job log prefixes "job<TAB>step<TAB>" and a timestamp; a downloaded
    # step log the timestamp alone.
    sub(/^.*[0-9]T[0-9:.]+Z /, "", line)
    if (line ~ /^(::|##\[)group(::|\])shard [0-9]+/) { inside = 1; next }
    if (line ~ /^(::|##\[)endgroup(::|\])/) { inside = 0; next }
    if (!inside) next
    if (line ~ /^=== PAUSE Test/) {
      split(line, f, " ")
      paused[f[3]] = 1
      next
    }
    if (line ~ /^(    )?--- (PASS|FAIL): Test[^ ]+ \([0-9.]+s\)$/) {
      n = split(line, f, " ")
      secs = f[n]
      gsub(/[()s]/, "", secs)
      name = f[n - 1]
      if (name in paused) secs = secs / par
      if (line ~ /^---/) {
        own[name] = secs
      } else if (name in paused) {
        sub(/\/.*$/, "", name)
        subs[name] += secs
      }
    }
  }
  END {
    for (name in own) {
      secs = own[name] + subs[name]
      if (secs + 0 >= min + 0) printf "%.2f %s\n", secs, name
    }
  }
' | sort -k1,1nr -k2,2
