package render

import (
	"encoding/base64"
	"fmt"
	"os"
	"path/filepath"
	"testing"
)

func TestCheckDependencies(t *testing.T) {
	// This test verifies that checkDep returns a sensible error for
	// a command that definitely doesn't exist.
	err := checkDep("definitely-not-a-real-command-12345")
	if err == nil {
		t.Fatal("expected error for missing command")
	}
	if got := err.Error(); got == "" {
		t.Fatal("expected non-empty error message")
	}
}

func TestRenderSlide_FileNotFound(t *testing.T) {
	_, err := RenderSlide("/tmp/nonexistent-deck.pptx", 0, 100)
	if err == nil {
		t.Fatal("expected error for nonexistent file")
	}
}

func TestRenderDeck_FileNotFound(t *testing.T) {
	_, err := RenderDeck("/tmp/nonexistent-deck.pptx", 50, 10)
	if err == nil {
		t.Fatal("expected error for nonexistent file")
	}
}

func TestReadAsBase64(t *testing.T) {
	// Create a temp file with known content.
	f, err := os.CreateTemp("", "render-test-*.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer os.Remove(f.Name())

	content := []byte("hello world")
	if _, err := f.Write(content); err != nil {
		t.Fatal(err)
	}
	f.Close()

	b64, size, err := readAsBase64(f.Name())
	if err != nil {
		t.Fatal(err)
	}
	if size != len(content) {
		t.Errorf("size = %d, want %d", size, len(content))
	}
	if b64 == "" {
		t.Error("expected non-empty base64")
	}
}

// TestIntegrationRenderSlide tests actual rendering if dependencies are available.
// Skipped in CI if libreoffice/magick are not installed.
func TestIntegrationRenderSlide(t *testing.T) {
	if err := CheckDependencies(); err != nil {
		t.Skipf("skipping integration test: %v", err)
	}

	// Look for a test PPTX generated by the build step.
	pptxPath := "/tmp/render-test/basic-deck.pptx"
	if _, err := os.Stat(pptxPath); os.IsNotExist(err) {
		t.Skipf("skipping: test PPTX not found at %s (run generate first)", pptxPath)
	}

	img, err := RenderSlide(pptxPath, 0, 72)
	if err != nil {
		t.Fatalf("RenderSlide failed: %v", err)
	}

	if img.PNG64 == "" && img.Path == "" {
		t.Fatal("expected either PNG64 or Path to be set")
	}

	if img.PNG64 != "" {
		data, err := base64.StdEncoding.DecodeString(img.PNG64)
		if err != nil {
			t.Fatalf("invalid base64: %v", err)
		}
		// PNG magic bytes
		if len(data) < 8 || string(data[:4]) != "\x89PNG" {
			t.Fatal("decoded data is not a valid PNG")
		}
	}
}

func TestCacheKeyDiffersByDensity(t *testing.T) {
	k1 := cacheKey("abc123", 50)
	k2 := cacheKey("abc123", 100)
	if k1 == k2 {
		t.Fatal("cache keys should differ for different densities")
	}
}

func TestCacheKeyDiffersByHash(t *testing.T) {
	k1 := cacheKey("hash1", 50)
	k2 := cacheKey("hash2", 50)
	if k1 == k2 {
		t.Fatal("cache keys should differ for different hashes")
	}
}

func TestHashFile(t *testing.T) {
	f, err := os.CreateTemp("", "render-hash-*.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer os.Remove(f.Name())

	if _, err := f.Write([]byte("content A")); err != nil {
		t.Fatal(err)
	}
	f.Close()

	h1, err := hashFile(f.Name())
	if err != nil {
		t.Fatal(err)
	}
	if h1 == "" {
		t.Fatal("expected non-empty hash")
	}

	// Same content => same hash
	h2, err := hashFile(f.Name())
	if err != nil {
		t.Fatal(err)
	}
	if h1 != h2 {
		t.Fatal("same file should produce same hash")
	}

	// Change content => different hash
	if err := os.WriteFile(f.Name(), []byte("content B"), 0644); err != nil {
		t.Fatal(err)
	}
	h3, err := hashFile(f.Name())
	if err != nil {
		t.Fatal(err)
	}
	if h1 == h3 {
		t.Fatal("different content should produce different hash")
	}
}

func TestGetCachedPNGs_Miss(t *testing.T) {
	result := getCachedPNGs("nonexistent-key-12345")
	if result != nil {
		t.Fatal("expected nil for cache miss")
	}
}

func TestStoreCacheAndRetrieve(t *testing.T) {
	// Create temp PNGs
	tmpDir, err := os.MkdirTemp("", "cache-test-*")
	if err != nil {
		t.Fatal(err)
	}
	defer os.RemoveAll(tmpDir)

	var pngs []string
	for i := 0; i < 3; i++ {
		p := filepath.Join(tmpDir, fmt.Sprintf("slide-%d.png", i))
		if err := os.WriteFile(p, []byte(fmt.Sprintf("png-data-%d", i)), 0644); err != nil {
			t.Fatal(err)
		}
		pngs = append(pngs, p)
	}

	key := "test-store-retrieve-key"
	// Clean up after test
	defer os.RemoveAll(filepath.Join(cacheDir(), key))

	storeCachePNGs(key, pngs)

	cached := getCachedPNGs(key)
	if len(cached) != 3 {
		t.Fatalf("expected 3 cached PNGs, got %d", len(cached))
	}

	// Verify content
	for i, path := range cached {
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatal(err)
		}
		expected := fmt.Sprintf("png-data-%d", i)
		if string(data) != expected {
			t.Errorf("cached file %d: got %q, want %q", i, string(data), expected)
		}
	}
}

func TestIntegrationRenderDeck(t *testing.T) {
	if err := CheckDependencies(); err != nil {
		t.Skipf("skipping integration test: %v", err)
	}

	pptxPath := "/tmp/render-test/basic-deck.pptx"
	if _, err := os.Stat(pptxPath); os.IsNotExist(err) {
		t.Skipf("skipping: test PPTX not found at %s", pptxPath)
	}

	result, err := RenderDeck(pptxPath, 50, 3)
	if err != nil {
		t.Fatalf("RenderDeck failed: %v", err)
	}

	if len(result.Slides) == 0 {
		t.Fatal("expected at least one slide")
	}
	if len(result.Slides) > 3 {
		t.Errorf("expected at most 3 slides, got %d", len(result.Slides))
	}
	// The basic-deck has 7 slides, so truncated should be true with max=3
	if !result.Truncated {
		t.Error("expected truncated=true with max_slides=3 on a 7-slide deck")
	}
}
