package render

import (
	"encoding/base64"
	"os"
	"testing"
)

func TestCheckDependencies(t *testing.T) {
	// This test verifies that checkDep returns a sensible error for
	// a command that definitely doesn't exist.
	err := checkDep("definitely-not-a-real-command-12345")
	if err == nil {
		t.Fatal("expected error for missing command")
	}
	if got := err.Error(); got == "" {
		t.Fatal("expected non-empty error message")
	}
}

func TestRenderSlide_FileNotFound(t *testing.T) {
	_, err := RenderSlide("/tmp/nonexistent-deck.pptx", 0, 100)
	if err == nil {
		t.Fatal("expected error for nonexistent file")
	}
}

func TestRenderDeck_FileNotFound(t *testing.T) {
	_, err := RenderDeck("/tmp/nonexistent-deck.pptx", 50, 10)
	if err == nil {
		t.Fatal("expected error for nonexistent file")
	}
}

func TestReadAsBase64(t *testing.T) {
	// Create a temp file with known content.
	f, err := os.CreateTemp("", "render-test-*.txt")
	if err != nil {
		t.Fatal(err)
	}
	defer os.Remove(f.Name())

	content := []byte("hello world")
	if _, err := f.Write(content); err != nil {
		t.Fatal(err)
	}
	f.Close()

	b64, size, err := readAsBase64(f.Name())
	if err != nil {
		t.Fatal(err)
	}
	if size != len(content) {
		t.Errorf("size = %d, want %d", size, len(content))
	}
	if b64 == "" {
		t.Error("expected non-empty base64")
	}
}

// TestIntegrationRenderSlide tests actual rendering if dependencies are available.
// Skipped in CI if libreoffice/magick are not installed.
func TestIntegrationRenderSlide(t *testing.T) {
	if err := CheckDependencies(); err != nil {
		t.Skipf("skipping integration test: %v", err)
	}

	// Look for a test PPTX generated by the build step.
	pptxPath := "/tmp/render-test/basic-deck.pptx"
	if _, err := os.Stat(pptxPath); os.IsNotExist(err) {
		t.Skipf("skipping: test PPTX not found at %s (run generate first)", pptxPath)
	}

	img, err := RenderSlide(pptxPath, 0, 72)
	if err != nil {
		t.Fatalf("RenderSlide failed: %v", err)
	}

	if img.PNG64 == "" && img.Path == "" {
		t.Fatal("expected either PNG64 or Path to be set")
	}

	if img.PNG64 != "" {
		data, err := base64.StdEncoding.DecodeString(img.PNG64)
		if err != nil {
			t.Fatalf("invalid base64: %v", err)
		}
		// PNG magic bytes
		if len(data) < 8 || string(data[:4]) != "\x89PNG" {
			t.Fatal("decoded data is not a valid PNG")
		}
	}
}

func TestIntegrationRenderDeck(t *testing.T) {
	if err := CheckDependencies(); err != nil {
		t.Skipf("skipping integration test: %v", err)
	}

	pptxPath := "/tmp/render-test/basic-deck.pptx"
	if _, err := os.Stat(pptxPath); os.IsNotExist(err) {
		t.Skipf("skipping: test PPTX not found at %s", pptxPath)
	}

	result, err := RenderDeck(pptxPath, 50, 3)
	if err != nil {
		t.Fatalf("RenderDeck failed: %v", err)
	}

	if len(result.Slides) == 0 {
		t.Fatal("expected at least one slide")
	}
	if len(result.Slides) > 3 {
		t.Errorf("expected at most 3 slides, got %d", len(result.Slides))
	}
	// The basic-deck has 7 slides, so truncated should be true with max=3
	if !result.Truncated {
		t.Error("expected truncated=true with max_slides=3 on a 7-slide deck")
	}
}
