// Package svggen provides SVG diagram generation using canvas primitives.
// This file registers all built-in diagram types with the default registry.
package svggen

// builtinDiagrams lists all diagram types to register at startup.
// Adding a new diagram type only requires appending to this slice.
var builtinDiagrams = []Diagram{
	// Phase 1-2: core chart and diagram types
	&WaterfallDiagram{NewBaseDiagram("waterfall")},
	&Matrix2x2Diagram{NewBaseDiagram("matrix_2x2")},
	&Timeline{NewBaseDiagram("timeline")},

	// Phase 3: funnel, gauge, treemap
	&FunnelDiagram{NewBaseDiagram("funnel_chart")},
	&GaugeDiagram{NewBaseDiagram("gauge_chart")},
	&TreemapDiagram{NewBaseDiagram("treemap_chart")},

	// Phase 4: venn (swot migrated to native OOXML)
	&VennDiagram{NewBaseDiagram("venn")},

	// Phase 5: org chart, gantt
	&OrgChartDiagram{NewBaseDiagram("org_chart")},
	&GanttDiagram{NewBaseDiagram("gantt")},

	// Phase 7: fishbone (heatmap, pestel migrated to native OOXML)
	&FishboneDiagram{NewBaseDiagram("fishbone")},

	// Standard chart types (bar, line, pie, donut, area, radar, scatter, stacked, bubble, grouped)
	&BarChartDiagram{NewBaseDiagram("bar_chart")},
	&LineChartDiagram{NewBaseDiagram("line_chart")},
	&PieChartDiagram{NewBaseDiagram("pie_chart")},
	&DonutChartDiagram{NewBaseDiagram("donut_chart")},
	&AreaChartDiagram{NewBaseDiagram("area_chart")},
	&RadarChartDiagram{NewBaseDiagram("radar_chart")},
	&ScatterChartDiagram{NewBaseDiagram("scatter_chart")},
	&StackedBarChartDiagram{NewBaseDiagram("stacked_bar_chart")},
	&BubbleChartDiagram{NewBaseDiagram("bubble_chart")},
	&StackedAreaChartDiagram{NewBaseDiagram("stacked_area_chart")},
	&GroupedBarChartDiagram{NewBaseDiagram("grouped_bar_chart")},
}

// builtinAliases maps short/alternate names to canonical registered type IDs.
// This allows users to write "funnel" instead of "funnel_chart" in diagram blocks.
var builtinAliases = map[string]string{
	// Chart short names
	"funnel":       "funnel_chart",
	"gauge":        "gauge_chart",
	"treemap":      "treemap_chart",
	"bar":          "bar_chart",
	"line":         "line_chart",
	"pie":          "pie_chart",
	"donut":        "donut_chart",
	"area":         "area_chart",
	"radar":        "radar_chart",
	"scatter":      "scatter_chart",
	"bubble":       "bubble_chart",
	"stacked_bar":  "stacked_bar_chart",
	"stacked_area": "stacked_area_chart",
	"grouped_bar":  "grouped_bar_chart",
	"bar-stacked":  "stacked_bar_chart",

	// Diagram alternate names (commonly generated by LLMs)
	"orgchart": "org_chart",
	"org":      "org_chart",
	"matrix":   "matrix_2x2",
}

func init() {
	for _, d := range builtinDiagrams {
		Register(d)
	}
	for alias, canonical := range builtinAliases {
		Alias(alias, canonical)
	}
}
